# Generated by Django 4.0 on 2023-03-10 19:29

import authentication_sd.custom_fields.cpf_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', authentication_sd.custom_fields.cpf_field.CPFField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
